version: "3"
services:
  # database:
  #   image: postgis/postgis:13-master
  #   # Required when running on platform other than amd64, like Apple M1/M2:
  #   # platform: linux/amd64
  #   ports:
  #     - 5432:5432   
  #   volumes:
  #     - ./data/database:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: "directus"
  #     POSTGRES_PASSWORD: "directus"
  #     POSTGRES_DB: "directus"
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # cache:
  #   image: redis:6
  #   # platform: linux/amd64
  #   healthcheck:
  #     test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  directus:
    # platform: linux/amd64
    build:
      context: .
    ports:
      - 8055:8055    
    volumes:
      - ./extensions:/usr/src/app/extensions 



      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"

    # Environment variables can also be defined in a file (for example `.env`):
    env_file:
      - .env